CREATE TABLE IF NOT EXISTS transactions (
    transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id INTEGER NOT NULL REFERENCES accounts(account_id),
    instrument_id INTEGER REFERENCES instruments(instrument_id),
    transaction_type TEXT NOT NULL CHECK(transaction_type IN ('buy','sell','deposit','withdrawal','dividend','interest','fee','tax','transfer_in','transfer_out','reversal','correction')),
    trade_date TEXT NOT NULL,
    settlement_date TEXT,
    currency TEXT NOT NULL CHECK(length(currency) = 3),
    quantity DECIMAL_TEXT CHECK(quantity IS NULL OR typeof(quantity) = 'text'),
    price DECIMAL_TEXT CHECK(price IS NULL OR typeof(price) = 'text'),
    gross_amount DECIMAL_TEXT NOT NULL CHECK(typeof(gross_amount) = 'text'),
    fee_amount DECIMAL_TEXT NOT NULL DEFAULT '0' CHECK(typeof(fee_amount) = 'text'),
    tax_amount DECIMAL_TEXT NOT NULL DEFAULT '0' CHECK(typeof(tax_amount) = 'text'),
    net_cash_amount DECIMAL_TEXT NOT NULL CHECK(typeof(net_cash_amount) = 'text'),
    fx_rate_to_base DECIMAL_TEXT CHECK(fx_rate_to_base IS NULL OR typeof(fx_rate_to_base) = 'text'),
    source TEXT NOT NULL DEFAULT 'manual' CHECK(source IN ('manual','csv_import','external_snapshot','system_correction')),
    external_ref TEXT,
    description TEXT,
    is_confirmed INTEGER NOT NULL DEFAULT 0 CHECK(is_confirmed IN (0,1)),
    is_voided INTEGER NOT NULL DEFAULT 0 CHECK(is_voided IN (0,1)),
    void_reason TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    CHECK(is_voided = 0 OR void_reason IS NOT NULL),
    CHECK(transaction_type NOT IN ('buy','sell') OR (instrument_id IS NOT NULL AND quantity IS NOT NULL AND price IS NOT NULL))
);
