CREATE TABLE IF NOT EXISTS reconciliation_snapshots (
    reconciliation_id INTEGER PRIMARY KEY AUTOINCREMENT,
    account_id INTEGER REFERENCES accounts(account_id),
    as_of_date TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    ledger_status_before TEXT NOT NULL CHECK(ledger_status_before IN ('reconciled','provisional','stale','broken')),
    ledger_status_after TEXT NOT NULL CHECK(ledger_status_after IN ('reconciled','provisional','stale','broken')),
    reconciliation_status TEXT NOT NULL CHECK(reconciliation_status IN ('passed','failed','needs_review')),
    snapshot_source TEXT NOT NULL CHECK(snapshot_source IN ('manual','csv_import','external_statement')),
    position_diff_count INTEGER NOT NULL DEFAULT 0 CHECK(position_diff_count >= 0),
    cash_diff_count INTEGER NOT NULL DEFAULT 0 CHECK(cash_diff_count >= 0),
    liability_diff_count INTEGER NOT NULL DEFAULT 0 CHECK(liability_diff_count >= 0),
    tax_reserve_diff_count INTEGER NOT NULL DEFAULT 0 CHECK(tax_reserve_diff_count >= 0),
    total_abs_cash_diff_base DECIMAL_TEXT NOT NULL DEFAULT '0' CHECK(typeof(total_abs_cash_diff_base) = 'text'),
    tolerance_cash_abs DECIMAL_TEXT NOT NULL DEFAULT '0' CHECK(typeof(tolerance_cash_abs) = 'text'),
    tolerance_quantity_abs DECIMAL_TEXT NOT NULL DEFAULT '0' CHECK(typeof(tolerance_quantity_abs) = 'text'),
    expected_positions_json TEXT NOT NULL DEFAULT '[]',
    actual_positions_json TEXT NOT NULL DEFAULT '[]',
    position_diffs_json TEXT NOT NULL DEFAULT '[]',
    expected_cash_json TEXT NOT NULL DEFAULT '[]',
    actual_cash_json TEXT NOT NULL DEFAULT '[]',
    cash_diffs_json TEXT NOT NULL DEFAULT '[]',
    expected_liabilities_json TEXT NOT NULL DEFAULT '[]',
    actual_liabilities_json TEXT NOT NULL DEFAULT '[]',
    liability_diffs_json TEXT NOT NULL DEFAULT '[]',
    expected_tax_reserves_json TEXT NOT NULL DEFAULT '[]',
    actual_tax_reserves_json TEXT NOT NULL DEFAULT '[]',
    tax_reserve_diffs_json TEXT NOT NULL DEFAULT '[]',
    failure_reason TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
    CHECK(reconciliation_status != 'passed' OR ledger_status_after = 'reconciled'),
    CHECK(reconciliation_status != 'failed' OR ledger_status_after = 'broken'),
    CHECK(reconciliation_status != 'needs_review' OR ledger_status_after IN ('provisional','broken')),
    CHECK(completed_at IS NULL OR completed_at >= started_at),
    CHECK(reconciliation_status != 'passed' OR (position_diff_count = 0 AND cash_diff_count = 0 AND liability_diff_count = 0 AND tax_reserve_diff_count = 0))
);
