import { useAccountsQuery } from "../../api/queries/accounts";
import { useInstrumentsQuery } from "../../api/queries/instruments";
import { useLedgerSnapshotQuery } from "../../api/queries/ledger";
import type { Account, Instrument, LedgerCash, LedgerLiability, LedgerPosition, LedgerTaxReserve } from "../../api/types";
import { DataTable, type DataColumn } from "../../components/tables/DataTable";
import { StatusBadge } from "../../components/status/StatusBadge";
import { errorMessage } from "../../lib/guards";
import { formatDate, formatDecimal, formatMoney } from "../../lib/format";

const accountColumns: DataColumn<Account>[] = [{ key: "name", header: "계좌", render: (r) => r.account_name }, { key: "institution", header: "기관", render: (r) => r.institution_name }, { key: "type", header: "유형", render: (r) => r.account_type }, { key: "currency", header: "기준 통화", render: (r) => r.base_currency }, { key: "status", header: "상태", render: (r) => <StatusBadge label={r.is_active ? "활성" : "비활성"} tone={r.is_active ? "green" : "gray"} /> }];
const instrumentColumns: DataColumn<Instrument>[] = [{ key: "symbol", header: "심볼", render: (r) => <span className="mono accent">{r.symbol}</span> }, { key: "name", header: "종목명", render: (r) => r.instrument_name }, { key: "type", header: "유형", render: (r) => r.instrument_type }, { key: "market", header: "시장", render: (r) => r.exchange ?? "-" }, { key: "currency", header: "통화", render: (r) => r.currency }];
const positionColumns: DataColumn<LedgerPosition>[] = [{ key: "symbol", header: "심볼", render: (r) => <span className="mono accent">{r.symbol}</span> }, { key: "account", header: "계좌 ID", render: (r) => r.account_id }, { key: "qty", header: "수량", align: "right", render: (r) => formatDecimal(r.quantity) }, { key: "cost", header: "평균원가", align: "right", render: (r) => r.average_cost ? formatMoney(r.average_cost, r.currency) : "-" }];
const cashColumns: DataColumn<LedgerCash>[] = [{ key: "account", header: "계좌 ID", render: (r) => r.account_id }, { key: "currency", header: "통화", render: (r) => r.currency }, { key: "amount", header: "금액", align: "right", render: (r) => formatMoney(r.amount, r.currency) }];
const liabilityColumns: DataColumn<LedgerLiability>[] = [{ key: "name", header: "부채", render: (r) => r.liability_name }, { key: "type", header: "유형", render: (r) => r.liability_type }, { key: "amount", header: "현재 금액", align: "right", render: (r) => formatMoney(r.current_amount, r.currency) }];
const taxColumns: DataColumn<LedgerTaxReserve>[] = [{ key: "year", header: "연도", render: (r) => r.tax_year }, { key: "type", header: "유형", render: (r) => r.tax_type }, { key: "amount", header: "준비금", align: "right", render: (r) => formatMoney(r.reserved_amount, r.currency) }];

export function LedgerPage() {
  const accounts = useAccountsQuery(); const instruments = useInstrumentsQuery(); const snapshot = useLedgerSnapshotQuery(); const error = accounts.error ?? instruments.error ?? snapshot.error;
  return <div className="page"><header className="page-heading"><div><p className="eyebrow">LEDGER TRUTH</p><h1>레저</h1><p>{snapshot.data ? `${formatDate(snapshot.data.as_of_date)} 기준 스냅샷` : "계좌와 레저 스냅샷을 조회합니다."}</p></div><span className="read-only-tag">READ ONLY</span></header>{error && <div className="inline-error" role="alert">{errorMessage(error)}</div>}
    <div className="two-column"><section className="panel"><div className="panel__header"><h2>계좌 <span>{accounts.data?.count ?? 0}</span></h2></div><DataTable columns={accountColumns} rows={accounts.data?.accounts ?? []} rowKey={(r) => r.account_id} emptyMessage="등록된 계좌가 없습니다." caption="계좌 목록" /></section><section className="panel"><div className="panel__header"><h2>종목 <span>{instruments.data?.count ?? 0}</span></h2></div><DataTable columns={instrumentColumns} rows={instruments.data?.instruments ?? []} rowKey={(r) => r.instrument_id} emptyMessage="등록된 종목이 없습니다." caption="종목 목록" /></section></div>
    <section className="panel"><div className="panel__header"><h2>포지션</h2></div><DataTable columns={positionColumns} rows={snapshot.data?.positions ?? []} rowKey={(r) => `${r.account_id}-${r.instrument_id}`} emptyMessage="현재 포지션이 없습니다." caption="레저 포지션" /></section>
    <div className="three-column"><section className="panel"><div className="panel__header"><h2>현금</h2></div><DataTable columns={cashColumns} rows={snapshot.data?.cash ?? []} rowKey={(r) => `${r.account_id}-${r.currency}`} emptyMessage="현금 항목이 없습니다." caption="현금" /></section><section className="panel"><div className="panel__header"><h2>부채</h2></div><DataTable columns={liabilityColumns} rows={snapshot.data?.liabilities ?? []} rowKey={(r) => r.liability_id} emptyMessage="부채 항목이 없습니다." caption="부채" /></section><section className="panel"><div className="panel__header"><h2>세금 준비금</h2></div><DataTable columns={taxColumns} rows={snapshot.data?.tax_reserves ?? []} rowKey={(r) => r.tax_reserve_id} emptyMessage="세금 준비금이 없습니다." caption="세금 준비금" /></section></div>
  </div>;
}
